export const OPEN_ADMIN_PANEL = "OPEN_ADMIN_PANEL";
export const CLOSE_ADMIN_PANEL = "CLOSE_ADMIN_PANEL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_HASERROR = "GET_ALL_USERS_HASERROR";

export const DELETE_CURRENT_USER_REQUEST = "DELETE_CURRENT_USER";
export const DELETE_CURRENT_USER_SUCCESS = "DELETE_CURRENT_USER_SUCCESS";
export const DELETE_CURRENT_USER_HASERROR = "DELETE_CURRENT_USER_HASERROR";

export const SAVE_USERS_CHANGES_REQUEST = "SAVE_USERS_CHANGES_REQUEST";
export const SAVE_USERS_CHANGES_HASERROR = "SAVE_USERS_CHANGES_HASERROR";
