export const GET_INDICATORS_DATA_REQUEST = 'GET_INDICATORS_DATA_REQUEST'
export const GET_INDICATORS_DATA_SUCCESS = 'GET_INDICATORS_DATA_SUCCESS'
export const GET_INDICATORS_DATA_FAILURE = 'GET_INDICATORS_DATA_FAILURE'
export const GET_INDICATORS_DATA_CLEAR = 'GET_INDICATORS_DATA_CLEAR'
