SELECT id                             AS id,
       day_rate_delivery              AS late_delivery_rate,
       day_rate_payment               AS late_payment_rate,
       forfeit_day_rate               AS late_guarantee_rate,
       guarantee_provision            AS guarantee_percent,
       max_deductible_amount_delivery AS max_deductible_amount_delivery,
       max_deductible_amount_payment  AS max_deductible_amount_payment,
       max_deductible_amount          AS max_deductible_amount_guarantee,
       allow_guarantee                AS has_guarantee,
       allow_insurance                AS has_insurance,
       allow_related_service          AS has_related_services,
       allow_spares                   AS has_spares,
       allow_technical_control        AS has_technical_control,
       allow_advance                  AS has_prepayment,
       allow_after_acceptance         AS has_acceptance_payment,
       allow_after_shipment           AS has_shipment_payment,
       advance                        AS prepayment_percent,
       after_acceptance               AS acceptance_payment_percent,
       after_shipment                 AS shipment_payment_percent,
       insurance                      AS insurance_type,
       court_type                     AS has_arbitral_tribunal
FROM conditions_of_contract
WHERE order_id = ?
