export const GET_REGIONS_TOP_PROCUREMENT_REQUEST = 'GET_REGIONS_TOP_PROCUREMENT_REQUEST'
export const GET_REGIONS_TOP_PROCUREMENT_SUCCESS = 'GET_REGIONS_TOP_PROCUREMENT_SUCCESS'
export const GET_REGIONS_TOP_PROCUREMENT_FAILURE = 'GET_REGIONS_TOP_PROCUREMENT_FAILURE'
export const GET_REGIONS_TOP_PROCUREMENT_CLEAR = 'GET_REGIONS_TOP_PROCUREMENT_CLEAR'

export const GET_REGIONS_COMPETITIVITY_PROCUREMENT_REQUEST = 'GET_REGIONS_COMPETITIVITY_PROCUREMENT_REQUEST'
export const GET_REGIONS_COMPETITIVITY_PROCUREMENT_SUCCESS = 'GET_REGIONS_COMPETITIVITY_PROCUREMENT_SUCCESS'
export const GET_REGIONS_COMPETITIVITY_PROCUREMENT_FAILURE = 'GET_REGIONS_COMPETITIVITY_PROCUREMENT_FAILURE'
export const GET_REGIONS_COMPETITIVITY_PROCUREMENT_CLEAR = 'GET_REGIONS_COMPETITIVITY_PROCUREMENT_CLEAR'

export const LOCALITY_REQUEST = 'LOCALITY_REQUEST'
export const LOCALITY_SUCCESS = 'LOCALITY_SUCCESS'
export const LOCALITY_FAILURE = 'LOCALITY_FAILURE'
export const LOCALITY_CLEAR = 'LOCALITY_CLEAR'

export const WHAT_TO_BUY_REGIONS_REQUEST = 'WHAT_TO_BUY_REGIONS_REQUEST'
export const WHAT_TO_BUY_REGIONS_SUCCESS = 'WHAT_TO_BUY_REGIONS_SUCCESS'
export const WHAT_TO_BUY_REGIONS_FAILURE = 'WHAT_TO_BUY_REGIONS_FAILURE'
export const WHAT_TO_BUY_REGIONS_CLEAR = 'WHAT_TO_BUY_REGIONS_CLEAR'
