export const GET_EXPLORATION_DATA_REQUEST = 'GET_EXPLORATION_DATA_REQUEST'
export const GET_EXPLORATION_DATA_SUCCESS = 'GET_EXPLORATION_DATA_SUCCESS'
export const GET_EXPLORATION_DATA_FAILURE = 'GET_EXPLORATION_DATA_FAILURE'
export const GET_EXPLORATION_DATA_CLEAR = 'GET_EXPLORATION_DATA_CLEAR'

