export const GET_STATISTIC_DATA_REQUEST = 'GET_STATISTIC_DATA_REQUEST'
export const GET_STATISTIC_DATA_SUCCESS = 'GET_STATISTIC_DATA_SUCCESS'
export const GET_STATISTIC_DATA_FAILURE = 'GET_STATISTIC_DATA_FAILURE'
export const GET_STATISTIC_DATA_CLEAR = 'GET_STATISTIC_DATA_CLEAR'

