export const LOGIN = 'login/'
export const LOGOUT = 'logout/'

export const GET_USERS = 'getUsers/'
export const DELETE_USER = 'deleteUserById/'
export const CREATE_NEW_USER = 'createUser/'
export const REGISTER_NEW_USER = 'registerUser/'
export const SEND_RESTORE_EMAIL = 'sendRestoreEmail/'
export const CHECK_RESTORE_PASSWORD_TOKEN = 'checkRestoreToken/'
export const SAVE_NEW_PASSWORD = 'saveNewResetPassword/'
export const SET_USER_JWT = 'setUserToken/'
