export const GET_JSON_DATA_REQUEST = 'GET_JSON_DATA_REQUEST'
export const GET_JSON_DATA_SUCCESS = 'GET_JSON_DATA_SUCCESS'
export const GET_JSON_DATA_FAILURE = 'GET_JSON_DATA_FAILURE'
export const GET_JSON_DATA_CLEAR = 'GET_JSON_DATA_CLEAR'

export const GET_CSV_DATA_REQUEST = 'GET_CSV_DATA_REQUEST'
export const GET_CSV_DATA_SUCCESS = 'GET_CSV_DATA_SUCCESS'
export const GET_CSV_DATA_FAILURE = 'GET_CSV_DATA_FAILURE'
export const GET_CSV_DATA_CLEAR = 'GET_CSV_DATA_CLEAR'

export const PROC_EXPORT_REQUEST = 'PROC_EXPORT_REQUEST'
export const PROC_EXPORT_SUCCESS = 'PROC_EXPORT_SUCCESS'
export const PROC_EXPORT_FAILURE = 'PROC_EXPORT_FAILURE'
export const PROC_EXPORT_CLEAR = 'PROC_EXPORT_CLEAR'

